// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	coupon "looklook/app/coupon/cmd/api/internal/handler/coupon"
	"looklook/app/coupon/cmd/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 可领取的优惠券列表
				Method:  http.MethodPost,
				Path:    "/coupon/templateList",
				Handler: coupon.TemplateListHandler(serverCtx),
			},
		},
		rest.WithPrefix("/coupon/v1"),
	)

	server.AddRoutes(
		[]rest.Route{
			{
				// 领取优惠券
				Method:  http.MethodPost,
				Path:    "/coupon/claim",
				Handler: coupon.ClaimHandler(serverCtx),
			},
			{
				// 我的优惠券
				Method:  http.MethodPost,
				Path:    "/coupon/myCoupons",
				Handler: coupon.MyCouponsHandler(serverCtx),
			},
			{
				// 下单前预览可用券
				Method:  http.MethodPost,
				Path:    "/coupon/previewCoupon",
				Handler: coupon.PreviewCouponHandler(serverCtx),
			},
		},
		rest.WithJwt(serverCtx.Config.JwtAuth.AccessSecret),
		rest.WithPrefix("/coupon/v1"),
	)
}
