// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.36.2
// source: coupon.proto

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Coupon_TemplateList_FullMethodName    = "/pb.coupon/templateList"
	Coupon_ClaimCoupon_FullMethodName     = "/pb.coupon/claimCoupon"
	Coupon_ListUserCoupons_FullMethodName = "/pb.coupon/listUserCoupons"
	Coupon_PreviewCoupon_FullMethodName   = "/pb.coupon/previewCoupon"
	Coupon_LockCoupon_FullMethodName      = "/pb.coupon/lockCoupon"
	Coupon_UseCoupon_FullMethodName       = "/pb.coupon/useCoupon"
	Coupon_ReleaseCoupon_FullMethodName   = "/pb.coupon/releaseCoupon"
)

// CouponClient is the client API for Coupon service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CouponClient interface {
	// 可领券列表
	TemplateList(ctx context.Context, in *TemplateListReq, opts ...grpc.CallOption) (*TemplateListResp, error)
	// 领取券
	ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error)
	// 我的券
	ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error)
	// 预览可用券
	PreviewCoupon(ctx context.Context, in *PreviewCouponReq, opts ...grpc.CallOption) (*PreviewCouponResp, error)
	// 下单锁定券
	LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*LockCouponResp, error)
	// 支付成功后核销
	UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error)
	// 订单取消/超时释放
	ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*ReleaseCouponResp, error)
}

type couponClient struct {
	cc grpc.ClientConnInterface
}

func NewCouponClient(cc grpc.ClientConnInterface) CouponClient {
	return &couponClient{cc}
}

func (c *couponClient) TemplateList(ctx context.Context, in *TemplateListReq, opts ...grpc.CallOption) (*TemplateListResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TemplateListResp)
	err := c.cc.Invoke(ctx, Coupon_TemplateList_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ClaimCouponResp)
	err := c.cc.Invoke(ctx, Coupon_ClaimCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUserCouponsResp)
	err := c.cc.Invoke(ctx, Coupon_ListUserCoupons_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) PreviewCoupon(ctx context.Context, in *PreviewCouponReq, opts ...grpc.CallOption) (*PreviewCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(PreviewCouponResp)
	err := c.cc.Invoke(ctx, Coupon_PreviewCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*LockCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(LockCouponResp)
	err := c.cc.Invoke(ctx, Coupon_LockCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UseCouponResp)
	err := c.cc.Invoke(ctx, Coupon_UseCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *couponClient) ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*ReleaseCouponResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReleaseCouponResp)
	err := c.cc.Invoke(ctx, Coupon_ReleaseCoupon_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CouponServer is the server API for Coupon service.
// All implementations must embed UnimplementedCouponServer
// for forward compatibility.
type CouponServer interface {
	// 可领券列表
	TemplateList(context.Context, *TemplateListReq) (*TemplateListResp, error)
	// 领取券
	ClaimCoupon(context.Context, *ClaimCouponReq) (*ClaimCouponResp, error)
	// 我的券
	ListUserCoupons(context.Context, *ListUserCouponsReq) (*ListUserCouponsResp, error)
	// 预览可用券
	PreviewCoupon(context.Context, *PreviewCouponReq) (*PreviewCouponResp, error)
	// 下单锁定券
	LockCoupon(context.Context, *LockCouponReq) (*LockCouponResp, error)
	// 支付成功后核销
	UseCoupon(context.Context, *UseCouponReq) (*UseCouponResp, error)
	// 订单取消/超时释放
	ReleaseCoupon(context.Context, *ReleaseCouponReq) (*ReleaseCouponResp, error)
	mustEmbedUnimplementedCouponServer()
}

// UnimplementedCouponServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCouponServer struct{}

func (UnimplementedCouponServer) TemplateList(context.Context, *TemplateListReq) (*TemplateListResp, error) {
	return nil, status.Error(codes.Unimplemented, "method TemplateList not implemented")
}
func (UnimplementedCouponServer) ClaimCoupon(context.Context, *ClaimCouponReq) (*ClaimCouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ClaimCoupon not implemented")
}
func (UnimplementedCouponServer) ListUserCoupons(context.Context, *ListUserCouponsReq) (*ListUserCouponsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUserCoupons not implemented")
}
func (UnimplementedCouponServer) PreviewCoupon(context.Context, *PreviewCouponReq) (*PreviewCouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method PreviewCoupon not implemented")
}
func (UnimplementedCouponServer) LockCoupon(context.Context, *LockCouponReq) (*LockCouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method LockCoupon not implemented")
}
func (UnimplementedCouponServer) UseCoupon(context.Context, *UseCouponReq) (*UseCouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UseCoupon not implemented")
}
func (UnimplementedCouponServer) ReleaseCoupon(context.Context, *ReleaseCouponReq) (*ReleaseCouponResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ReleaseCoupon not implemented")
}
func (UnimplementedCouponServer) mustEmbedUnimplementedCouponServer() {}
func (UnimplementedCouponServer) testEmbeddedByValue()                {}

// UnsafeCouponServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CouponServer will
// result in compilation errors.
type UnsafeCouponServer interface {
	mustEmbedUnimplementedCouponServer()
}

func RegisterCouponServer(s grpc.ServiceRegistrar, srv CouponServer) {
	// If the following call panics, it indicates UnimplementedCouponServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Coupon_ServiceDesc, srv)
}

func _Coupon_TemplateList_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TemplateListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).TemplateList(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_TemplateList_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).TemplateList(ctx, req.(*TemplateListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_ClaimCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ClaimCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).ClaimCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_ClaimCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).ClaimCoupon(ctx, req.(*ClaimCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_ListUserCoupons_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUserCouponsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).ListUserCoupons(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_ListUserCoupons_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).ListUserCoupons(ctx, req.(*ListUserCouponsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_PreviewCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PreviewCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).PreviewCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_PreviewCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).PreviewCoupon(ctx, req.(*PreviewCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_LockCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LockCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).LockCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_LockCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).LockCoupon(ctx, req.(*LockCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_UseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UseCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).UseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_UseCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).UseCoupon(ctx, req.(*UseCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _Coupon_ReleaseCoupon_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReleaseCouponReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CouponServer).ReleaseCoupon(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Coupon_ReleaseCoupon_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CouponServer).ReleaseCoupon(ctx, req.(*ReleaseCouponReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Coupon_ServiceDesc is the grpc.ServiceDesc for Coupon service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Coupon_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "pb.coupon",
	HandlerType: (*CouponServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "templateList",
			Handler:    _Coupon_TemplateList_Handler,
		},
		{
			MethodName: "claimCoupon",
			Handler:    _Coupon_ClaimCoupon_Handler,
		},
		{
			MethodName: "listUserCoupons",
			Handler:    _Coupon_ListUserCoupons_Handler,
		},
		{
			MethodName: "previewCoupon",
			Handler:    _Coupon_PreviewCoupon_Handler,
		},
		{
			MethodName: "lockCoupon",
			Handler:    _Coupon_LockCoupon_Handler,
		},
		{
			MethodName: "useCoupon",
			Handler:    _Coupon_UseCoupon_Handler,
		},
		{
			MethodName: "releaseCoupon",
			Handler:    _Coupon_ReleaseCoupon_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "coupon.proto",
}
