// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.2
// source: coupon.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// 券模板
type CouponTemplate struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Type           int64                  `protobuf:"varint,3,opt,name=type,proto3" json:"type,omitempty"`                     //1:满减
	DiscountAmount int64                  `protobuf:"varint,4,opt,name=discountAmount,proto3" json:"discountAmount,omitempty"` //优惠金额(分)
	MinAmount      int64                  `protobuf:"varint,5,opt,name=minAmount,proto3" json:"minAmount,omitempty"`           //使用门槛(分)
	TotalCount     int64                  `protobuf:"varint,6,opt,name=totalCount,proto3" json:"totalCount,omitempty"`         //发行总量
	IssuedCount    int64                  `protobuf:"varint,7,opt,name=issuedCount,proto3" json:"issuedCount,omitempty"`       //已发放数量
	PerUserLimit   int64                  `protobuf:"varint,8,opt,name=perUserLimit,proto3" json:"perUserLimit,omitempty"`     //每人限领
	ValidStart     int64                  `protobuf:"varint,9,opt,name=validStart,proto3" json:"validStart,omitempty"`         //有效期起(时间戳)
	ValidEnd       int64                  `protobuf:"varint,10,opt,name=validEnd,proto3" json:"validEnd,omitempty"`            //有效期止(时间戳)
	Status         int64                  `protobuf:"varint,11,opt,name=status,proto3" json:"status,omitempty"`                //1:上架 0:下架
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CouponTemplate) Reset() {
	*x = CouponTemplate{}
	mi := &file_coupon_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CouponTemplate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CouponTemplate) ProtoMessage() {}

func (x *CouponTemplate) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CouponTemplate.ProtoReflect.Descriptor instead.
func (*CouponTemplate) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{0}
}

func (x *CouponTemplate) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *CouponTemplate) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CouponTemplate) GetType() int64 {
	if x != nil {
		return x.Type
	}
	return 0
}

func (x *CouponTemplate) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *CouponTemplate) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *CouponTemplate) GetTotalCount() int64 {
	if x != nil {
		return x.TotalCount
	}
	return 0
}

func (x *CouponTemplate) GetIssuedCount() int64 {
	if x != nil {
		return x.IssuedCount
	}
	return 0
}

func (x *CouponTemplate) GetPerUserLimit() int64 {
	if x != nil {
		return x.PerUserLimit
	}
	return 0
}

func (x *CouponTemplate) GetValidStart() int64 {
	if x != nil {
		return x.ValidStart
	}
	return 0
}

func (x *CouponTemplate) GetValidEnd() int64 {
	if x != nil {
		return x.ValidEnd
	}
	return 0
}

func (x *CouponTemplate) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 用户券
type UserCoupon struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId         int64                  `protobuf:"varint,2,opt,name=userId,proto3" json:"userId,omitempty"`
	TemplateId     int64                  `protobuf:"varint,3,opt,name=templateId,proto3" json:"templateId,omitempty"`
	CouponCode     string                 `protobuf:"bytes,4,opt,name=couponCode,proto3" json:"couponCode,omitempty"`
	Status         int64                  `protobuf:"varint,5,opt,name=status,proto3" json:"status,omitempty"`  //0:未使用 1:已锁定 2:已核销 3:已过期
	OrderSn        string                 `protobuf:"bytes,6,opt,name=orderSn,proto3" json:"orderSn,omitempty"` //占用的订单号
	LockTime       int64                  `protobuf:"varint,7,opt,name=lockTime,proto3" json:"lockTime,omitempty"`
	UseTime        int64                  `protobuf:"varint,8,opt,name=useTime,proto3" json:"useTime,omitempty"`
	ExpireTime     int64                  `protobuf:"varint,9,opt,name=expireTime,proto3" json:"expireTime,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,10,opt,name=discountAmount,proto3" json:"discountAmount,omitempty"` //优惠金额(分)，领取时的快照
	MinAmount      int64                  `protobuf:"varint,11,opt,name=minAmount,proto3" json:"minAmount,omitempty"`           //使用门槛(分)，领取时的快照
	Name           string                 `protobuf:"bytes,12,opt,name=name,proto3" json:"name,omitempty"`                      //券名称(展示用，实时取自模板，不做快照)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UserCoupon) Reset() {
	*x = UserCoupon{}
	mi := &file_coupon_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserCoupon) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserCoupon) ProtoMessage() {}

func (x *UserCoupon) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserCoupon.ProtoReflect.Descriptor instead.
func (*UserCoupon) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{1}
}

func (x *UserCoupon) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserCoupon) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *UserCoupon) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

func (x *UserCoupon) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *UserCoupon) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UserCoupon) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *UserCoupon) GetLockTime() int64 {
	if x != nil {
		return x.LockTime
	}
	return 0
}

func (x *UserCoupon) GetUseTime() int64 {
	if x != nil {
		return x.UseTime
	}
	return 0
}

func (x *UserCoupon) GetExpireTime() int64 {
	if x != nil {
		return x.ExpireTime
	}
	return 0
}

func (x *UserCoupon) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *UserCoupon) GetMinAmount() int64 {
	if x != nil {
		return x.MinAmount
	}
	return 0
}

func (x *UserCoupon) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

// 可领券列表
type TemplateListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LastId        int64                  `protobuf:"varint,1,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize      int64                  `protobuf:"varint,2,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateListReq) Reset() {
	*x = TemplateListReq{}
	mi := &file_coupon_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateListReq) ProtoMessage() {}

func (x *TemplateListReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateListReq.ProtoReflect.Descriptor instead.
func (*TemplateListReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{2}
}

func (x *TemplateListReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *TemplateListReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type TemplateListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*CouponTemplate      `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TemplateListResp) Reset() {
	*x = TemplateListResp{}
	mi := &file_coupon_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TemplateListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TemplateListResp) ProtoMessage() {}

func (x *TemplateListResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TemplateListResp.ProtoReflect.Descriptor instead.
func (*TemplateListResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{3}
}

func (x *TemplateListResp) GetList() []*CouponTemplate {
	if x != nil {
		return x.List
	}
	return nil
}

// 领取券
type ClaimCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	TemplateId    int64                  `protobuf:"varint,2,opt,name=templateId,proto3" json:"templateId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponReq) Reset() {
	*x = ClaimCouponReq{}
	mi := &file_coupon_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponReq) ProtoMessage() {}

func (x *ClaimCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponReq.ProtoReflect.Descriptor instead.
func (*ClaimCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{4}
}

func (x *ClaimCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ClaimCouponReq) GetTemplateId() int64 {
	if x != nil {
		return x.TemplateId
	}
	return 0
}

type ClaimCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CouponCode    string                 `protobuf:"bytes,1,opt,name=couponCode,proto3" json:"couponCode,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClaimCouponResp) Reset() {
	*x = ClaimCouponResp{}
	mi := &file_coupon_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClaimCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClaimCouponResp) ProtoMessage() {}

func (x *ClaimCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClaimCouponResp.ProtoReflect.Descriptor instead.
func (*ClaimCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{5}
}

func (x *ClaimCouponResp) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

// 我的券
type ListUserCouponsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Status        int64                  `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"` //-1:全部
	LastId        int64                  `protobuf:"varint,3,opt,name=lastId,proto3" json:"lastId,omitempty"`
	PageSize      int64                  `protobuf:"varint,4,opt,name=pageSize,proto3" json:"pageSize,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsReq) Reset() {
	*x = ListUserCouponsReq{}
	mi := &file_coupon_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsReq) ProtoMessage() {}

func (x *ListUserCouponsReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsReq.ProtoReflect.Descriptor instead.
func (*ListUserCouponsReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{6}
}

func (x *ListUserCouponsReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *ListUserCouponsReq) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *ListUserCouponsReq) GetLastId() int64 {
	if x != nil {
		return x.LastId
	}
	return 0
}

func (x *ListUserCouponsReq) GetPageSize() int64 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListUserCouponsResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*UserCoupon          `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUserCouponsResp) Reset() {
	*x = ListUserCouponsResp{}
	mi := &file_coupon_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUserCouponsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUserCouponsResp) ProtoMessage() {}

func (x *ListUserCouponsResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUserCouponsResp.ProtoReflect.Descriptor instead.
func (*ListUserCouponsResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{7}
}

func (x *ListUserCouponsResp) GetList() []*UserCoupon {
	if x != nil {
		return x.List
	}
	return nil
}

// 下单前预览可用券
type PreviewCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Amount        int64                  `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"` //订单原价(分)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewCouponReq) Reset() {
	*x = PreviewCouponReq{}
	mi := &file_coupon_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewCouponReq) ProtoMessage() {}

func (x *PreviewCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewCouponReq.ProtoReflect.Descriptor instead.
func (*PreviewCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{8}
}

func (x *PreviewCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *PreviewCouponReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type PreviewCouponItem struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	CouponCode     string                 `protobuf:"bytes,1,opt,name=couponCode,proto3" json:"couponCode,omitempty"`
	DiscountAmount int64                  `protobuf:"varint,2,opt,name=discountAmount,proto3" json:"discountAmount,omitempty"` //可抵扣金额(分)
	FinalAmount    int64                  `protobuf:"varint,3,opt,name=finalAmount,proto3" json:"finalAmount,omitempty"`       //抵扣后金额(分)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *PreviewCouponItem) Reset() {
	*x = PreviewCouponItem{}
	mi := &file_coupon_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewCouponItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewCouponItem) ProtoMessage() {}

func (x *PreviewCouponItem) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewCouponItem.ProtoReflect.Descriptor instead.
func (*PreviewCouponItem) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{9}
}

func (x *PreviewCouponItem) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *PreviewCouponItem) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *PreviewCouponItem) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

type PreviewCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	List          []*PreviewCouponItem   `protobuf:"bytes,1,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PreviewCouponResp) Reset() {
	*x = PreviewCouponResp{}
	mi := &file_coupon_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PreviewCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PreviewCouponResp) ProtoMessage() {}

func (x *PreviewCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PreviewCouponResp.ProtoReflect.Descriptor instead.
func (*PreviewCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{10}
}

func (x *PreviewCouponResp) GetList() []*PreviewCouponItem {
	if x != nil {
		return x.List
	}
	return nil
}

// 下单锁定券（order-rpc 调用，必须幂等）
type LockCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        int64                  `protobuf:"varint,1,opt,name=userId,proto3" json:"userId,omitempty"`
	CouponCode    string                 `protobuf:"bytes,2,opt,name=couponCode,proto3" json:"couponCode,omitempty"`
	OrderSn       string                 `protobuf:"bytes,3,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	Amount        int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"` // 订单原价(分)，用于在锁券时重新校验使用门槛
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LockCouponReq) Reset() {
	*x = LockCouponReq{}
	mi := &file_coupon_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockCouponReq) ProtoMessage() {}

func (x *LockCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockCouponReq.ProtoReflect.Descriptor instead.
func (*LockCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{11}
}

func (x *LockCouponReq) GetUserId() int64 {
	if x != nil {
		return x.UserId
	}
	return 0
}

func (x *LockCouponReq) GetCouponCode() string {
	if x != nil {
		return x.CouponCode
	}
	return ""
}

func (x *LockCouponReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

func (x *LockCouponReq) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

type LockCouponResp struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DiscountAmount int64                  `protobuf:"varint,1,opt,name=discountAmount,proto3" json:"discountAmount,omitempty"` //实际抵扣金额(分)
	FinalAmount    int64                  `protobuf:"varint,2,opt,name=finalAmount,proto3" json:"finalAmount,omitempty"`       //抵扣后应付金额(分)
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *LockCouponResp) Reset() {
	*x = LockCouponResp{}
	mi := &file_coupon_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LockCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LockCouponResp) ProtoMessage() {}

func (x *LockCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LockCouponResp.ProtoReflect.Descriptor instead.
func (*LockCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{12}
}

func (x *LockCouponResp) GetDiscountAmount() int64 {
	if x != nil {
		return x.DiscountAmount
	}
	return 0
}

func (x *LockCouponResp) GetFinalAmount() int64 {
	if x != nil {
		return x.FinalAmount
	}
	return 0
}

// 支付成功后核销（order-mq 调用，必须幂等）
type UseCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponReq) Reset() {
	*x = UseCouponReq{}
	mi := &file_coupon_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponReq) ProtoMessage() {}

func (x *UseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponReq.ProtoReflect.Descriptor instead.
func (*UseCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{13}
}

func (x *UseCouponReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type UseCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UseCouponResp) Reset() {
	*x = UseCouponResp{}
	mi := &file_coupon_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UseCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UseCouponResp) ProtoMessage() {}

func (x *UseCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UseCouponResp.ProtoReflect.Descriptor instead.
func (*UseCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{14}
}

// 订单取消/超时释放（order-rpc / 定时任务调用，必须幂等）
type ReleaseCouponReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderSn       string                 `protobuf:"bytes,1,opt,name=orderSn,proto3" json:"orderSn,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCouponReq) Reset() {
	*x = ReleaseCouponReq{}
	mi := &file_coupon_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCouponReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCouponReq) ProtoMessage() {}

func (x *ReleaseCouponReq) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCouponReq.ProtoReflect.Descriptor instead.
func (*ReleaseCouponReq) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{15}
}

func (x *ReleaseCouponReq) GetOrderSn() string {
	if x != nil {
		return x.OrderSn
	}
	return ""
}

type ReleaseCouponResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseCouponResp) Reset() {
	*x = ReleaseCouponResp{}
	mi := &file_coupon_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseCouponResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseCouponResp) ProtoMessage() {}

func (x *ReleaseCouponResp) ProtoReflect() protoreflect.Message {
	mi := &file_coupon_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseCouponResp.ProtoReflect.Descriptor instead.
func (*ReleaseCouponResp) Descriptor() ([]byte, []int) {
	return file_coupon_proto_rawDescGZIP(), []int{16}
}

var File_coupon_proto protoreflect.FileDescriptor

const file_coupon_proto_rawDesc = "" +
	"\n" +
	"\fcoupon.proto\x12\x02pb\"\xc8\x02\n" +
	"\x0eCouponTemplate\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x03 \x01(\x03R\x04type\x12&\n" +
	"\x0ediscountAmount\x18\x04 \x01(\x03R\x0ediscountAmount\x12\x1c\n" +
	"\tminAmount\x18\x05 \x01(\x03R\tminAmount\x12\x1e\n" +
	"\n" +
	"totalCount\x18\x06 \x01(\x03R\n" +
	"totalCount\x12 \n" +
	"\vissuedCount\x18\a \x01(\x03R\vissuedCount\x12\"\n" +
	"\fperUserLimit\x18\b \x01(\x03R\fperUserLimit\x12\x1e\n" +
	"\n" +
	"validStart\x18\t \x01(\x03R\n" +
	"validStart\x12\x1a\n" +
	"\bvalidEnd\x18\n" +
	" \x01(\x03R\bvalidEnd\x12\x16\n" +
	"\x06status\x18\v \x01(\x03R\x06status\"\xd6\x02\n" +
	"\n" +
	"UserCoupon\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x16\n" +
	"\x06userId\x18\x02 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"templateId\x18\x03 \x01(\x03R\n" +
	"templateId\x12\x1e\n" +
	"\n" +
	"couponCode\x18\x04 \x01(\tR\n" +
	"couponCode\x12\x16\n" +
	"\x06status\x18\x05 \x01(\x03R\x06status\x12\x18\n" +
	"\aorderSn\x18\x06 \x01(\tR\aorderSn\x12\x1a\n" +
	"\blockTime\x18\a \x01(\x03R\blockTime\x12\x18\n" +
	"\auseTime\x18\b \x01(\x03R\auseTime\x12\x1e\n" +
	"\n" +
	"expireTime\x18\t \x01(\x03R\n" +
	"expireTime\x12&\n" +
	"\x0ediscountAmount\x18\n" +
	" \x01(\x03R\x0ediscountAmount\x12\x1c\n" +
	"\tminAmount\x18\v \x01(\x03R\tminAmount\x12\x12\n" +
	"\x04name\x18\f \x01(\tR\x04name\"E\n" +
	"\x0fTemplateListReq\x12\x16\n" +
	"\x06lastId\x18\x01 \x01(\x03R\x06lastId\x12\x1a\n" +
	"\bpageSize\x18\x02 \x01(\x03R\bpageSize\":\n" +
	"\x10TemplateListResp\x12&\n" +
	"\x04list\x18\x01 \x03(\v2\x12.pb.CouponTemplateR\x04list\"H\n" +
	"\x0eClaimCouponReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"templateId\x18\x02 \x01(\x03R\n" +
	"templateId\"1\n" +
	"\x0fClaimCouponResp\x12\x1e\n" +
	"\n" +
	"couponCode\x18\x01 \x01(\tR\n" +
	"couponCode\"x\n" +
	"\x12ListUserCouponsReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\x03R\x06status\x12\x16\n" +
	"\x06lastId\x18\x03 \x01(\x03R\x06lastId\x12\x1a\n" +
	"\bpageSize\x18\x04 \x01(\x03R\bpageSize\"9\n" +
	"\x13ListUserCouponsResp\x12\"\n" +
	"\x04list\x18\x01 \x03(\v2\x0e.pb.UserCouponR\x04list\"B\n" +
	"\x10PreviewCouponReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x16\n" +
	"\x06amount\x18\x02 \x01(\x03R\x06amount\"}\n" +
	"\x11PreviewCouponItem\x12\x1e\n" +
	"\n" +
	"couponCode\x18\x01 \x01(\tR\n" +
	"couponCode\x12&\n" +
	"\x0ediscountAmount\x18\x02 \x01(\x03R\x0ediscountAmount\x12 \n" +
	"\vfinalAmount\x18\x03 \x01(\x03R\vfinalAmount\">\n" +
	"\x11PreviewCouponResp\x12)\n" +
	"\x04list\x18\x01 \x03(\v2\x15.pb.PreviewCouponItemR\x04list\"y\n" +
	"\rLockCouponReq\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\x03R\x06userId\x12\x1e\n" +
	"\n" +
	"couponCode\x18\x02 \x01(\tR\n" +
	"couponCode\x12\x18\n" +
	"\aorderSn\x18\x03 \x01(\tR\aorderSn\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\"Z\n" +
	"\x0eLockCouponResp\x12&\n" +
	"\x0ediscountAmount\x18\x01 \x01(\x03R\x0ediscountAmount\x12 \n" +
	"\vfinalAmount\x18\x02 \x01(\x03R\vfinalAmount\"(\n" +
	"\fUseCouponReq\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\"\x0f\n" +
	"\rUseCouponResp\",\n" +
	"\x10ReleaseCouponReq\x12\x18\n" +
	"\aorderSn\x18\x01 \x01(\tR\aorderSn\"\x13\n" +
	"\x11ReleaseCouponResp2\xa2\x03\n" +
	"\x06coupon\x129\n" +
	"\ftemplateList\x12\x13.pb.TemplateListReq\x1a\x14.pb.TemplateListResp\x126\n" +
	"\vclaimCoupon\x12\x12.pb.ClaimCouponReq\x1a\x13.pb.ClaimCouponResp\x12B\n" +
	"\x0flistUserCoupons\x12\x16.pb.ListUserCouponsReq\x1a\x17.pb.ListUserCouponsResp\x12<\n" +
	"\rpreviewCoupon\x12\x14.pb.PreviewCouponReq\x1a\x15.pb.PreviewCouponResp\x123\n" +
	"\n" +
	"lockCoupon\x12\x11.pb.LockCouponReq\x1a\x12.pb.LockCouponResp\x120\n" +
	"\tuseCoupon\x12\x10.pb.UseCouponReq\x1a\x11.pb.UseCouponResp\x12<\n" +
	"\rreleaseCoupon\x12\x14.pb.ReleaseCouponReq\x1a\x15.pb.ReleaseCouponRespB\x06Z\x04./pbb\x06proto3"

var (
	file_coupon_proto_rawDescOnce sync.Once
	file_coupon_proto_rawDescData []byte
)

func file_coupon_proto_rawDescGZIP() []byte {
	file_coupon_proto_rawDescOnce.Do(func() {
		file_coupon_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)))
	})
	return file_coupon_proto_rawDescData
}

var file_coupon_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_coupon_proto_goTypes = []any{
	(*CouponTemplate)(nil),      // 0: pb.CouponTemplate
	(*UserCoupon)(nil),          // 1: pb.UserCoupon
	(*TemplateListReq)(nil),     // 2: pb.TemplateListReq
	(*TemplateListResp)(nil),    // 3: pb.TemplateListResp
	(*ClaimCouponReq)(nil),      // 4: pb.ClaimCouponReq
	(*ClaimCouponResp)(nil),     // 5: pb.ClaimCouponResp
	(*ListUserCouponsReq)(nil),  // 6: pb.ListUserCouponsReq
	(*ListUserCouponsResp)(nil), // 7: pb.ListUserCouponsResp
	(*PreviewCouponReq)(nil),    // 8: pb.PreviewCouponReq
	(*PreviewCouponItem)(nil),   // 9: pb.PreviewCouponItem
	(*PreviewCouponResp)(nil),   // 10: pb.PreviewCouponResp
	(*LockCouponReq)(nil),       // 11: pb.LockCouponReq
	(*LockCouponResp)(nil),      // 12: pb.LockCouponResp
	(*UseCouponReq)(nil),        // 13: pb.UseCouponReq
	(*UseCouponResp)(nil),       // 14: pb.UseCouponResp
	(*ReleaseCouponReq)(nil),    // 15: pb.ReleaseCouponReq
	(*ReleaseCouponResp)(nil),   // 16: pb.ReleaseCouponResp
}
var file_coupon_proto_depIdxs = []int32{
	0,  // 0: pb.TemplateListResp.list:type_name -> pb.CouponTemplate
	1,  // 1: pb.ListUserCouponsResp.list:type_name -> pb.UserCoupon
	9,  // 2: pb.PreviewCouponResp.list:type_name -> pb.PreviewCouponItem
	2,  // 3: pb.coupon.templateList:input_type -> pb.TemplateListReq
	4,  // 4: pb.coupon.claimCoupon:input_type -> pb.ClaimCouponReq
	6,  // 5: pb.coupon.listUserCoupons:input_type -> pb.ListUserCouponsReq
	8,  // 6: pb.coupon.previewCoupon:input_type -> pb.PreviewCouponReq
	11, // 7: pb.coupon.lockCoupon:input_type -> pb.LockCouponReq
	13, // 8: pb.coupon.useCoupon:input_type -> pb.UseCouponReq
	15, // 9: pb.coupon.releaseCoupon:input_type -> pb.ReleaseCouponReq
	3,  // 10: pb.coupon.templateList:output_type -> pb.TemplateListResp
	5,  // 11: pb.coupon.claimCoupon:output_type -> pb.ClaimCouponResp
	7,  // 12: pb.coupon.listUserCoupons:output_type -> pb.ListUserCouponsResp
	10, // 13: pb.coupon.previewCoupon:output_type -> pb.PreviewCouponResp
	12, // 14: pb.coupon.lockCoupon:output_type -> pb.LockCouponResp
	14, // 15: pb.coupon.useCoupon:output_type -> pb.UseCouponResp
	16, // 16: pb.coupon.releaseCoupon:output_type -> pb.ReleaseCouponResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_coupon_proto_init() }
func file_coupon_proto_init() {
	if File_coupon_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coupon_proto_rawDesc), len(file_coupon_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_coupon_proto_goTypes,
		DependencyIndexes: file_coupon_proto_depIdxs,
		MessageInfos:      file_coupon_proto_msgTypes,
	}.Build()
	File_coupon_proto = out.File
	file_coupon_proto_goTypes = nil
	file_coupon_proto_depIdxs = nil
}
