// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: coupon.proto

package server

import (
	"context"

	"looklook/app/coupon/cmd/rpc/internal/logic"
	"looklook/app/coupon/cmd/rpc/internal/svc"
	"looklook/app/coupon/cmd/rpc/pb"
)

type CouponServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedCouponServer
}

func NewCouponServer(svcCtx *svc.ServiceContext) *CouponServer {
	return &CouponServer{
		svcCtx: svcCtx,
	}
}

// 可领券列表
func (s *CouponServer) TemplateList(ctx context.Context, in *pb.TemplateListReq) (*pb.TemplateListResp, error) {
	l := logic.NewTemplateListLogic(ctx, s.svcCtx)
	return l.TemplateList(in)
}

// 领取券
func (s *CouponServer) ClaimCoupon(ctx context.Context, in *pb.ClaimCouponReq) (*pb.ClaimCouponResp, error) {
	l := logic.NewClaimCouponLogic(ctx, s.svcCtx)
	return l.ClaimCoupon(in)
}

// 我的券
func (s *CouponServer) ListUserCoupons(ctx context.Context, in *pb.ListUserCouponsReq) (*pb.ListUserCouponsResp, error) {
	l := logic.NewListUserCouponsLogic(ctx, s.svcCtx)
	return l.ListUserCoupons(in)
}

// 预览可用券
func (s *CouponServer) PreviewCoupon(ctx context.Context, in *pb.PreviewCouponReq) (*pb.PreviewCouponResp, error) {
	l := logic.NewPreviewCouponLogic(ctx, s.svcCtx)
	return l.PreviewCoupon(in)
}

// 下单锁定券
func (s *CouponServer) LockCoupon(ctx context.Context, in *pb.LockCouponReq) (*pb.LockCouponResp, error) {
	l := logic.NewLockCouponLogic(ctx, s.svcCtx)
	return l.LockCoupon(in)
}

// 支付成功后核销
func (s *CouponServer) UseCoupon(ctx context.Context, in *pb.UseCouponReq) (*pb.UseCouponResp, error) {
	l := logic.NewUseCouponLogic(ctx, s.svcCtx)
	return l.UseCoupon(in)
}

// 订单取消/超时释放
func (s *CouponServer) ReleaseCoupon(ctx context.Context, in *pb.ReleaseCouponReq) (*pb.ReleaseCouponResp, error) {
	l := logic.NewReleaseCouponLogic(ctx, s.svcCtx)
	return l.ReleaseCoupon(in)
}
