// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponUseRecordFieldNames          = builder.RawFieldNames(&CouponUseRecord{})
	couponUseRecordRows                = strings.Join(couponUseRecordFieldNames, ",")
	couponUseRecordRowsExpectAutoSet   = strings.Join(stringx.Remove(couponUseRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponUseRecordRowsWithPlaceHolder = strings.Join(stringx.Remove(couponUseRecordFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	couponUseRecordModel interface {
		Insert(ctx context.Context, data *CouponUseRecord) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CouponUseRecord, error)
		Update(ctx context.Context, data *CouponUseRecord) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCouponUseRecordModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CouponUseRecord struct {
		Id         int64     `db:"id"`
		CouponCode string    `db:"coupon_code"` // 券码
		UserId     int64     `db:"user_id"`     // 用户id
		OrderSn    string    `db:"order_sn"`    // 订单号
		Action     int64     `db:"action"`      // 1锁定 2核销 3释放 4过期
		Remark     string    `db:"remark"`      // 备注
		CreateTime time.Time `db:"create_time"`
	}
)

func newCouponUseRecordModel(conn sqlx.SqlConn) *defaultCouponUseRecordModel {
	return &defaultCouponUseRecordModel{
		conn:  conn,
		table: "`coupon_use_record`",
	}
}

func (m *defaultCouponUseRecordModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCouponUseRecordModel) FindOne(ctx context.Context, id int64) (*CouponUseRecord, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponUseRecordRows, m.table)
	var resp CouponUseRecord
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponUseRecordModel) Insert(ctx context.Context, data *CouponUseRecord) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?)", m.table, couponUseRecordRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.CouponCode, data.UserId, data.OrderSn, data.Action, data.Remark)
	return ret, err
}

func (m *defaultCouponUseRecordModel) Update(ctx context.Context, data *CouponUseRecord) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponUseRecordRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.CouponCode, data.UserId, data.OrderSn, data.Action, data.Remark, data.Id)
	return err
}

func (m *defaultCouponUseRecordModel) tableName() string {
	return m.table
}
