// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	couponTemplateFieldNames          = builder.RawFieldNames(&CouponTemplate{})
	couponTemplateRows                = strings.Join(couponTemplateFieldNames, ",")
	couponTemplateRowsExpectAutoSet   = strings.Join(stringx.Remove(couponTemplateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	couponTemplateRowsWithPlaceHolder = strings.Join(stringx.Remove(couponTemplateFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	couponTemplateModel interface {
		Insert(ctx context.Context, data *CouponTemplate) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CouponTemplate, error)
		Update(ctx context.Context, data *CouponTemplate) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCouponTemplateModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CouponTemplate struct {
		Id             int64     `db:"id"`
		Name           string    `db:"name"`            // 券名称
		Type           int64     `db:"type"`            // 券类型 1满减
		DiscountAmount int64     `db:"discount_amount"` // 优惠金额(分)
		MinAmount      int64     `db:"min_amount"`      // 使用门槛(分)
		TotalCount     int64     `db:"total_count"`     // 发行总量
		IssuedCount    int64     `db:"issued_count"`    // 已发放数量
		PerUserLimit   int64     `db:"per_user_limit"`  // 每人限领数量
		ValidStart     time.Time `db:"valid_start"`     // 有效期起
		ValidEnd       time.Time `db:"valid_end"`       // 有效期止
		Status         int64     `db:"status"`          // 1上架 0下架
		CreateTime     time.Time `db:"create_time"`
		UpdateTime     time.Time `db:"update_time"`
	}
)

func newCouponTemplateModel(conn sqlx.SqlConn) *defaultCouponTemplateModel {
	return &defaultCouponTemplateModel{
		conn:  conn,
		table: "`coupon_template`",
	}
}

func (m *defaultCouponTemplateModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCouponTemplateModel) FindOne(ctx context.Context, id int64) (*CouponTemplate, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", couponTemplateRows, m.table)
	var resp CouponTemplate
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCouponTemplateModel) Insert(ctx context.Context, data *CouponTemplate) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, couponTemplateRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Name, data.Type, data.DiscountAmount, data.MinAmount, data.TotalCount, data.IssuedCount, data.PerUserLimit, data.ValidStart, data.ValidEnd, data.Status)
	return ret, err
}

func (m *defaultCouponTemplateModel) Update(ctx context.Context, data *CouponTemplate) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, couponTemplateRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Name, data.Type, data.DiscountAmount, data.MinAmount, data.TotalCount, data.IssuedCount, data.PerUserLimit, data.ValidStart, data.ValidEnd, data.Status, data.Id)
	return err
}

func (m *defaultCouponTemplateModel) tableName() string {
	return m.table
}
