// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.10.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userCouponFieldNames          = builder.RawFieldNames(&UserCoupon{})
	userCouponRows                = strings.Join(userCouponFieldNames, ",")
	userCouponRowsExpectAutoSet   = strings.Join(stringx.Remove(userCouponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	userCouponRowsWithPlaceHolder = strings.Join(stringx.Remove(userCouponFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	userCouponModel interface {
		Insert(ctx context.Context, data *UserCoupon) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*UserCoupon, error)
		FindOneByCouponCode(ctx context.Context, couponCode string) (*UserCoupon, error)
		Update(ctx context.Context, data *UserCoupon) error
		Delete(ctx context.Context, id int64) error
	}

	defaultUserCouponModel struct {
		conn  sqlx.SqlConn
		table string
	}

	UserCoupon struct {
		Id             int64        `db:"id"`
		UserId         int64        `db:"user_id"`         // 持有用户id
		TemplateId     int64        `db:"template_id"`     // 券模板id
		DiscountAmount int64        `db:"discount_amount"` // 优惠金额(分,领取时快照)
		MinAmount      int64        `db:"min_amount"`      // 使用门槛(分,领取时快照)
		CouponCode     string       `db:"coupon_code"`     // 券码
		Status         int64        `db:"status"`          // 0未使用 1已锁定 2已核销 3已过期
		OrderSn        string       `db:"order_sn"`        // 占用的订单号
		LockTime       sql.NullTime `db:"lock_time"`       // 锁定时间
		UseTime        sql.NullTime `db:"use_time"`        // 核销时间
		ExpireTime     time.Time    `db:"expire_time"`     // 过期时间
		CreateTime     time.Time    `db:"create_time"`
		UpdateTime     time.Time    `db:"update_time"`
	}
)

func newUserCouponModel(conn sqlx.SqlConn) *defaultUserCouponModel {
	return &defaultUserCouponModel{
		conn:  conn,
		table: "`user_coupon`",
	}
}

func (m *defaultUserCouponModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultUserCouponModel) FindOne(ctx context.Context, id int64) (*UserCoupon, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", userCouponRows, m.table)
	var resp UserCoupon
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserCouponModel) FindOneByCouponCode(ctx context.Context, couponCode string) (*UserCoupon, error) {
	var resp UserCoupon
	query := fmt.Sprintf("select %s from %s where `coupon_code` = ? limit 1", userCouponRows, m.table)
	err := m.conn.QueryRowCtx(ctx, &resp, query, couponCode)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultUserCouponModel) Insert(ctx context.Context, data *UserCoupon) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, userCouponRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.UserId, data.TemplateId, data.DiscountAmount, data.MinAmount, data.CouponCode, data.Status, data.OrderSn, data.LockTime, data.UseTime, data.ExpireTime)
	return ret, err
}

func (m *defaultUserCouponModel) Update(ctx context.Context, newData *UserCoupon) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, userCouponRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, newData.UserId, newData.TemplateId, newData.DiscountAmount, newData.MinAmount, newData.CouponCode, newData.Status, newData.OrderSn, newData.LockTime, newData.UseTime, newData.ExpireTime, newData.Id)
	return err
}

func (m *defaultUserCouponModel) tableName() string {
	return m.table
}
