// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type ClaimReq struct {
	TemplateId int64 `json:"templateId"`
}

type ClaimResp struct {
	CouponCode string `json:"couponCode"`
}

type MyCouponsReq struct {
	Status   int64 `json:"status"` //-1:全部 0:未使用 1:已锁定 2:已核销 3:已过期
	LastId   int64 `json:"lastId"`
	PageSize int64 `json:"pageSize"`
}

type MyCouponsResp struct {
	List []UserCoupon `json:"list"`
}

type PreviewCouponItem struct {
	CouponCode     string `json:"couponCode"`
	DiscountAmount int64  `json:"discountAmount"` //可抵扣金额(分)
	FinalAmount    int64  `json:"finalAmount"`    //抵扣后金额(分)
}

type PreviewCouponReq struct {
	Amount int64 `json:"amount"` //订单原价(分)
}

type PreviewCouponResp struct {
	List []PreviewCouponItem `json:"list"`
}

type TemplateInfo struct {
	TemplateId     int64  `json:"templateId"`
	Name           string `json:"name"`
	DiscountAmount int64  `json:"discountAmount"` //优惠金额(分)
	MinAmount      int64  `json:"minAmount"`      //使用门槛(分)
	ValidStart     int64  `json:"validStart"`     //有效期起(时间戳)
	ValidEnd       int64  `json:"validEnd"`       //有效期止(时间戳)
	RemainCount    int64  `json:"remainCount"`    //剩余可领数量
}

type TemplateListReq struct {
	LastId   int64 `json:"lastId"`
	PageSize int64 `json:"pageSize"`
}

type TemplateListResp struct {
	List []TemplateInfo `json:"list"`
}

type UserCoupon struct {
	CouponCode     string `json:"couponCode"`     //券码
	Name           string `json:"name"`           //券名称
	DiscountAmount int64  `json:"discountAmount"` //优惠金额(分)
	MinAmount      int64  `json:"minAmount"`      //使用门槛(分)
	Status         int64  `json:"status"`         //0:未使用 1:已锁定 2:已核销 3:已过期
	ExpireTime     int64  `json:"expireTime"`     //过期时间(时间戳)
}
