// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: coupon.proto

package coupon

import (
	"context"

	"looklook/app/coupon/cmd/rpc/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ClaimCouponReq      = pb.ClaimCouponReq
	ClaimCouponResp     = pb.ClaimCouponResp
	CouponTemplate      = pb.CouponTemplate
	ListUserCouponsReq  = pb.ListUserCouponsReq
	ListUserCouponsResp = pb.ListUserCouponsResp
	LockCouponReq       = pb.LockCouponReq
	LockCouponResp      = pb.LockCouponResp
	PreviewCouponItem   = pb.PreviewCouponItem
	PreviewCouponReq    = pb.PreviewCouponReq
	PreviewCouponResp   = pb.PreviewCouponResp
	ReleaseCouponReq    = pb.ReleaseCouponReq
	ReleaseCouponResp   = pb.ReleaseCouponResp
	TemplateListReq     = pb.TemplateListReq
	TemplateListResp    = pb.TemplateListResp
	UseCouponReq        = pb.UseCouponReq
	UseCouponResp       = pb.UseCouponResp
	UserCoupon          = pb.UserCoupon

	Coupon interface {
		// 可领券列表
		TemplateList(ctx context.Context, in *TemplateListReq, opts ...grpc.CallOption) (*TemplateListResp, error)
		// 领取券
		ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error)
		// 我的券
		ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error)
		// 预览可用券
		PreviewCoupon(ctx context.Context, in *PreviewCouponReq, opts ...grpc.CallOption) (*PreviewCouponResp, error)
		// 下单锁定券
		LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*LockCouponResp, error)
		// 支付成功后核销
		UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error)
		// 订单取消/超时释放
		ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*ReleaseCouponResp, error)
	}

	defaultCoupon struct {
		cli zrpc.Client
	}
)

func NewCoupon(cli zrpc.Client) Coupon {
	return &defaultCoupon{
		cli: cli,
	}
}

// 可领券列表
func (m *defaultCoupon) TemplateList(ctx context.Context, in *TemplateListReq, opts ...grpc.CallOption) (*TemplateListResp, error) {
	client := pb.NewCouponClient(m.cli.Conn())
	return client.TemplateList(ctx, in, opts...)
}

// 领取券
func (m *defaultCoupon) ClaimCoupon(ctx context.Context, in *ClaimCouponReq, opts ...grpc.CallOption) (*ClaimCouponResp, error) {
	client := pb.NewCouponClient(m.cli.Conn())
	return client.ClaimCoupon(ctx, in, opts...)
}

// 我的券
func (m *defaultCoupon) ListUserCoupons(ctx context.Context, in *ListUserCouponsReq, opts ...grpc.CallOption) (*ListUserCouponsResp, error) {
	client := pb.NewCouponClient(m.cli.Conn())
	return client.ListUserCoupons(ctx, in, opts...)
}

// 预览可用券
func (m *defaultCoupon) PreviewCoupon(ctx context.Context, in *PreviewCouponReq, opts ...grpc.CallOption) (*PreviewCouponResp, error) {
	client := pb.NewCouponClient(m.cli.Conn())
	return client.PreviewCoupon(ctx, in, opts...)
}

// 下单锁定券
func (m *defaultCoupon) LockCoupon(ctx context.Context, in *LockCouponReq, opts ...grpc.CallOption) (*LockCouponResp, error) {
	client := pb.NewCouponClient(m.cli.Conn())
	return client.LockCoupon(ctx, in, opts...)
}

// 支付成功后核销
func (m *defaultCoupon) UseCoupon(ctx context.Context, in *UseCouponReq, opts ...grpc.CallOption) (*UseCouponResp, error) {
	client := pb.NewCouponClient(m.cli.Conn())
	return client.UseCoupon(ctx, in, opts...)
}

// 订单取消/超时释放
func (m *defaultCoupon) ReleaseCoupon(ctx context.Context, in *ReleaseCouponReq, opts ...grpc.CallOption) (*ReleaseCouponResp, error) {
	client := pb.NewCouponClient(m.cli.Conn())
	return client.ReleaseCoupon(ctx, in, opts...)
}
